id: PDD1B6AB1
initial_creation_type: ocr
source_metadata:
  volumes:
    4dc9dbdf7b2d44f1bb4df0f5d299d9cb:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: ག་ཡ་མགོའི་རིའི་རྣམ་པར་བཤད་པ།
      total_pages: 1498
      volume_number: 65
